# Generated by Django 2.2.18 on 2023-12-01 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('contact_details', models.TextField(max_length=200)),
                ('address', models.TextField(max_length=200)),
                ('vendor_code', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('on_time_delivery_rate', models.FloatField()),
                ('quality_rating_avg', models.FloatField()),
                ('average_response_time', models.FloatField()),
                ('fulfillment_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_order',
            fields=[
                ('po_number', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(verbose_name='date ordered')),
                ('delivery_date', models.DateTimeField(verbose_name='date delivered')),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(max_length=200)),
                ('quality_rating', models.FloatField()),
                ('issue_date', models.DateTimeField(verbose_name='date issued')),
                ('acknowledgement_date', models.DateTimeField(null=True, verbose_name='date acknowledged')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendmangr.Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('on_time_delivery_rate', models.FloatField()),
                ('quality_rating_avg', models.FloatField()),
                ('average_response_time', models.FloatField()),
                ('fulfillment_rate', models.FloatField()),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendmangr.Vendor')),
            ],
        ),
    ]
